import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
export type MemoryKind="episodic"|"semantic"|"procedural"|"project"|"preference"|"failure"|"evidence";
export type Memory2Item={id:string;kind:MemoryKind;content:string;tags:string[];sourceRef?:string;confidence:number;createdAt:string;updatedAt:string;hits:number;supersedes?:string};
const p=()=>path.resolve(process.env.JARVIS_MEMORY2_PATH||"./data/memory-v2.json");
async function read():Promise<Memory2Item[]>{try{return JSON.parse(await fs.readFile(p(),"utf8")) as Memory2Item[];}catch{return[];}}
async function save(x:Memory2Item[]){await fs.mkdir(path.dirname(p()),{recursive:true});await fs.writeFile(p(),JSON.stringify(x.slice(-10000),null,2),"utf8");}
const toks=(s:string)=>new Set(s.toLowerCase().split(/[^p{L}p{N}_-]+/u).filter(x=>x.length>2));
export async function remember2(args:{kind:MemoryKind;content:string;tags?:string[];sourceRef?:string;confidence?:number;supersedes?:string}){if(!args.content?.trim())throw new Error("content required");const now=new Date().toISOString(),all=await read();const dup=all.find(x=>x.kind===args.kind&&x.content.trim().toLowerCase()===args.content.trim().toLowerCase());if(dup){dup.hits++;dup.updatedAt=now;dup.confidence=Math.max(dup.confidence,Math.max(0,Math.min(1,args.confidence??dup.confidence)));await save(all);return dup;}const item:Memory2Item={id:`mem2_${randomUUID()}`,kind:args.kind,content:args.content.trim(),tags:args.tags||[],sourceRef:args.sourceRef,confidence:Math.max(0,Math.min(1,args.confidence??0.7)),createdAt:now,updatedAt:now,hits:1,supersedes:args.supersedes};all.push(item);await save(all);return item;}
export async function searchMemory2(query:string,limit=12,kinds?:MemoryKind[]){const q=toks(query),all=await read();return all.filter(x=>!kinds?.length||kinds.includes(x.kind)).map(x=>{const h=toks(`${x.content} ${x.tags.join(" ")}`);let overlap=0;for(const t of q)if(h.has(t))overlap++;return{...x,score:overlap*2+x.confidence+Math.log1p(x.hits)*.2}}).filter(x=>x.score>.5).sort((a,b)=>b.score-a.score||b.updatedAt.localeCompare(a.updatedAt)).slice(0,Math.max(1,Math.min(limit,50)));}
export async function consolidateMemory2(){const all=await read();const groups=new Map<string,Memory2Item[]>();for(const x of all){const key=`${x.kind}|${[...x.tags].sort().join(",")}`;groups.set(key,[...(groups.get(key)||[]),x]);}const candidates=[...groups.values()].filter(g=>g.length>=3).map(g=>({kind:g[0].kind,tags:g[0].tags,count:g.length,latest:g.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5).map(x=>x.content)}));return{items:all.length,consolidationCandidates:candidates.slice(0,50)};}
