import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";

export type MissionTaskStatus="todo"|"running"|"blocked"|"done"|"failed";
export type MissionTask={id:string;title:string;description?:string;dependsOn:string[];status:MissionTaskStatus;owner?:string;result?:string;updatedAt:string};
export type Mission={id:string;title:string;objective:string;constraints:string[];successMetrics:string[];budget?:{maxSteps?:number;maxCostUsd?:number};status:"active"|"paused"|"completed"|"cancelled";tasks:MissionTask[];createdAt:string;updatedAt:string};
const storePath=()=>path.resolve(process.env.JARVIS_MISSIONS_PATH||"./data/missions.json");
async function read():Promise<Mission[]>{try{return JSON.parse(await fs.readFile(storePath(),"utf8")) as Mission[];}catch{return[];}}
async function save(x:Mission[]){const p=storePath();await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,JSON.stringify(x.slice(-1000),null,2),"utf8");}
function validateDag(tasks:MissionTask[]){const ids=new Set(tasks.map(t=>t.id));for(const t of tasks)for(const d of t.dependsOn)if(!ids.has(d))throw new Error(`Unknown dependency ${d}`);const visiting=new Set<string>(),done=new Set<string>();const visit=(id:string)=>{if(done.has(id))return;if(visiting.has(id))throw new Error("Mission task graph contains a cycle.");visiting.add(id);for(const d of tasks.find(t=>t.id===id)!.dependsOn)visit(d);visiting.delete(id);done.add(id)};for(const t of tasks)visit(t.id);}
export async function createMission(args:{title:string;objective:string;constraints?:string[];successMetrics?:string[];tasks?:Array<{title:string;description?:string;dependsOn?:number[];owner?:string}>;budget?:Mission["budget"]}){if(!args.title?.trim()||!args.objective?.trim())throw new Error("title and objective are required.");const now=new Date().toISOString();const ids=(args.tasks||[]).map(()=>`task_${randomUUID()}`);const tasks=(args.tasks||[]).map((t,i):MissionTask=>({id:ids[i],title:t.title,description:t.description,dependsOn:(t.dependsOn||[]).map(j=>ids[j]).filter(Boolean),status:"todo",owner:t.owner,updatedAt:now}));validateDag(tasks);const m:Mission={id:`mission_${randomUUID()}`,title:args.title.trim(),objective:args.objective.trim(),constraints:args.constraints||[],successMetrics:args.successMetrics||[],budget:args.budget,status:"active",tasks,createdAt:now,updatedAt:now};const all=await read();all.push(m);await save(all);return m;}
export async function listMissions(limit=50){return (await read()).slice(-Math.max(1,Math.min(limit,200))).reverse();}
export async function updateMissionTask(args:{missionId:string;taskId:string;status:MissionTaskStatus;result?:string}){const all=await read();const m=all.find(x=>x.id===args.missionId);if(!m)throw new Error("Mission not found.");const t=m.tasks.find(x=>x.id===args.taskId);if(!t)throw new Error("Task not found.");if(args.status==="running"||args.status==="done"){const blocked=t.dependsOn.filter(id=>m.tasks.find(x=>x.id===id)?.status!=="done");if(blocked.length)throw new Error(`Dependencies not complete: ${blocked.join(", ")}`);}t.status=args.status;t.result=args.result;t.updatedAt=new Date().toISOString();m.updatedAt=t.updatedAt;if(m.tasks.length&&m.tasks.every(x=>x.status==="done"))m.status="completed";await save(all);return m;}
export async function missionStatus(id:string){const m=(await read()).find(x=>x.id===id);if(!m)throw new Error("Mission not found.");const ready=m.tasks.filter(t=>t.status==="todo"&&t.dependsOn.every(d=>m.tasks.find(x=>x.id===d)?.status==="done"));return{mission:m,readyTasks:ready,progress:m.tasks.length?m.tasks.filter(t=>t.status==="done").length/m.tasks.length:0};}
