import type { ToolCall,ToolExecutionResult } from "../types";
import { createMission,listMissions,missionStatus,updateMissionTask } from "./missions";
import { remember2,searchMemory2,consolidateMemory2 } from "./memory2";
import { teamPlan,AGENT_TEAM } from "./teams";
import { runCoreEvals } from "./evals";
import { sandboxStatus,sandboxRun } from "./sandbox";
import { listPlugins,registerPlugin,setPluginEnabled } from "./plugins";
import { proposeImprovement } from "./self-improvement";
import { quantRobustness } from "./quant-robustness";
import { commandCenterStatus } from "./command-center";
import { computerStatus,captureScreenshot } from "./computer";
import { meshWorkers,dispatchMeshWork } from "./distributed";
import { listPendingApprovals } from "../approvals";
import { securityState,setLockdown } from "./security-state";
import { addClaim,searchClaims } from "../research/claim-graph";
import { analyzeBookText } from "../knowledge/book-intelligence";
import { analyzePortfolio } from "../trading/portfolio";
import { microstructureFeatures } from "../trading/microstructure";
import { codingWorkflow } from "./coding-agent";
import { homeAssistantRequest } from "./iot";
import { visionTask } from "./vision";
import { eventRiskWindow } from "../trading/events";
import { convertUnit,dimensionCheck } from "../domains/units";
import { appraiseEvidence } from "../domains/evidence-appraisal";
import { authorityState,setAuthority,authorityPolicy } from "../cognition/authority";
import { upsertBelief,listBeliefs,reviseBelief } from "../cognition/beliefs";
import { enqueueThought,listThoughts,resolveThought } from "../cognition/queue";
import { runCognitionCycle,cognitionHistory } from "../cognition/cycle";
import { runIdleCycle } from "../cognition/idle";
const ok=(tool:string,data:unknown):ToolExecutionResult=>({ok:true,tool,summary:JSON.stringify(data,null,2),data});
export async function executeCoreTool(call:ToolCall):Promise<ToolExecutionResult>{
 const a=call.args as any;
 switch(call.tool){
 case"core.mission.create":return ok(call.tool,await createMission(a));
 case"core.mission.list":return ok(call.tool,await listMissions(Number(a.limit||50)));
 case"core.mission.status":return ok(call.tool,await missionStatus(String(a.id||"")));
 case"core.mission.task.update":return ok(call.tool,await updateMissionTask(a));
 case"core.memory.remember":return ok(call.tool,await remember2(a));
 case"core.memory.search":return ok(call.tool,await searchMemory2(String(a.query||""),Number(a.limit||12),a.kinds));
 case"core.memory.consolidate":return ok(call.tool,await consolidateMemory2());
 case"core.team.catalog":return ok(call.tool,AGENT_TEAM);
 case"core.team.plan":return ok(call.tool,teamPlan(a));
 case"core.eval.run":return ok(call.tool,await runCoreEvals());
 case"core.sandbox.status":return ok(call.tool,await sandboxStatus());
 case"core.sandbox.run":return ok(call.tool,await sandboxRun(a));
 case"core.plugins.list":return ok(call.tool,await listPlugins());
 case"core.plugins.register":return ok(call.tool,await registerPlugin(a));
 case"core.plugins.enable":return ok(call.tool,await setPluginEnabled(String(a.id||""),Boolean(a.enabled)));
 case"core.selfImprove.propose":return ok(call.tool,proposeImprovement(a));
 case"core.quant.robustness":return ok(call.tool,quantRobustness(a));
 case"core.commandCenter.status":return ok(call.tool,await commandCenterStatus());
 case"core.approvals.list":return ok(call.tool,await listPendingApprovals());
 case"core.computer.status":return ok(call.tool,await computerStatus());
 case"core.computer.screenshot":return ok(call.tool,await captureScreenshot());
 case"core.mesh.workers":return ok(call.tool,await meshWorkers());
 case"core.mesh.dispatch":return ok(call.tool,await dispatchMeshWork(a));
 case"core.security.status":return ok(call.tool,await securityState());
 case"core.security.lockdown":return ok(call.tool,await setLockdown(Boolean(a.enabled),a.reason?String(a.reason):undefined));
 case"core.claim.add":return ok(call.tool,await addClaim(a));
 case"core.claim.search":return ok(call.tool,await searchClaims(String(a.query||""),Number(a.limit||20)));
 case"core.book.analyze":return ok(call.tool,analyzeBookText(a));
 case"core.portfolio.analyze":return ok(call.tool,analyzePortfolio(a));
 case"core.microstructure.analyze":return ok(call.tool,microstructureFeatures(a));
 case"core.coding.workflow":return ok(call.tool,codingWorkflow(a));
 case"core.iot.plan":return ok(call.tool,homeAssistantRequest(a));
 case"core.vision.plan":return ok(call.tool,visionTask(a));
 case"core.events.window":return ok(call.tool,eventRiskWindow(a));
 case"core.units.convert":return ok(call.tool,convertUnit(a));
 case"core.units.check":return ok(call.tool,dimensionCheck(a));
 case"core.biomed.appraise":return ok(call.tool,appraiseEvidence(a));
 case"core.cognition.authority":{const st=await authorityState();return ok(call.tool,{state:st,policy:authorityPolicy(st.level)});}
 case"core.cognition.configure":return ok(call.tool,await setAuthority(a));
 case"core.cognition.run":return ok(call.tool,await runCognitionCycle(a));
 case"core.cognition.idle":return ok(call.tool,await runIdleCycle());
 case"core.cognition.history":return ok(call.tool,await cognitionHistory(Number(a.limit||50)));
 case"core.cognition.queue":return ok(call.tool,await listThoughts(Number(a.limit||100),a.status));
 case"core.cognition.enqueue":return ok(call.tool,await enqueueThought(a));
 case"core.cognition.resolve":return ok(call.tool,await resolveThought(String(a.id||""),a.status,a.result));
 case"core.belief.upsert":return ok(call.tool,await upsertBelief(a));
 case"core.belief.list":return ok(call.tool,await listBeliefs(Number(a.limit||100)));
 case"core.belief.revise":return ok(call.tool,await reviseBelief(a));
 default:return{ok:false,tool:call.tool,summary:"Core v1.5 tool not implemented.",error:"not implemented"};
 }}
