$ErrorActionPreference = 'Stop'
Write-Host 'JARVIS v1.2 Research Orchestrator setup/check'
Write-Host '1) Install Node dependencies for the web app:'
Write-Host '   npm install'
Write-Host '2) MT5 integration (Windows Python used by terminal):'
Write-Host '   py -m pip install MetaTrader5'
Write-Host '3) Optional engineering adapters are NOT auto-installed.'
Write-Host '   JARVIS can probe ngspice, ccx/CalculiX, gmsh, OpenFOAM and python-control.'
Write-Host '4) Configure .env.local from .env.example, then run:'
Write-Host '   npm run dev:lan'
Write-Host 'Use domain.engineering.adapters.doctor to see which optional scientific solvers are available.'
