import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { runResearchMatrix, buildChampionChallenger, type DatasetSpec, type CostScenario } from "./orchestrator";
import { evolvePopulation } from "./genome";
import { analyzeRegimes } from "./regimes";

type FactoryJobStatus="queued"|"running"|"completed"|"failed"|"cancelled";
type FactoryJob={id:string;createdAt:string;updatedAt:string;status:FactoryJobStatus;kind:"matrix"|"evolution"|"regime-scan"|"portfolio";payload:Record<string,unknown>;attempts:number;maxAttempts:number;result?:unknown;error?:string};
const storePath=()=>path.resolve(process.env.JARVIS_RESEARCH_FACTORY_PATH||"./data/research-factory.json");
async function read():Promise<FactoryJob[]>{try{return JSON.parse(await fs.readFile(storePath(),"utf8")) as FactoryJob[];}catch{return[];}}
async function save(x:FactoryJob[]){await fs.mkdir(path.dirname(storePath()),{recursive:true});await fs.writeFile(storePath(),JSON.stringify(x.slice(-5000),null,2),"utf8");}
export async function enqueueFactoryJob(kind:FactoryJob["kind"],payload:Record<string,unknown>,maxAttempts=2){const jobs=await read();const now=new Date().toISOString();const job:FactoryJob={id:`job_${randomUUID()}`,createdAt:now,updatedAt:now,status:"queued",kind,payload,attempts:0,maxAttempts:Math.max(1,Math.min(maxAttempts,5))};jobs.push(job);await save(jobs);return job;}
async function execute(job:FactoryJob){if(job.kind==="matrix")return runResearchMatrix(job.payload as {hypothesisIds?:string[];datasets:DatasetSpec[];costs?:CostScenario[];maxRuns?:number;seed?:string});if(job.kind==="evolution")return evolvePopulation(job.payload as any);if(job.kind==="regime-scan")return analyzeRegimes(job.payload as any);if(job.kind==="portfolio")return buildChampionChallenger(job.payload as any);throw new Error("Unsupported factory job.");}
export async function runFactory(args:{maxJobs?:number}={}){const jobs=await read();const limit=Math.max(1,Math.min(Number(args.maxJobs||20),100));let processed=0;for(const job of jobs){if(processed>=limit)break;if(job.status!=="queued"&&!(job.status==="failed"&&job.attempts<job.maxAttempts))continue;processed++;job.status="running";job.updatedAt=new Date().toISOString();job.attempts++;await save(jobs);try{job.result=await execute(job);job.status="completed";delete job.error;}catch(e){job.error=e instanceof Error?e.message:"unknown";job.status=job.attempts>=job.maxAttempts?"failed":"queued";}job.updatedAt=new Date().toISOString();await save(jobs);}return factoryStatus();}
export async function factoryStatus(){const jobs=await read();const byStatus=Object.fromEntries(["queued","running","completed","failed","cancelled"].map(s=>[s,jobs.filter(j=>j.status===s).length]));return{jobs:jobs.length,byStatus,recent:jobs.slice(-30).reverse()};}
export async function cancelFactoryJob(id:string){const jobs=await read();const j=jobs.find(x=>x.id===id);if(!j)throw new Error("Job not found.");if(j.status==="completed")throw new Error("Completed job cannot be cancelled.");j.status="cancelled";j.updatedAt=new Date().toISOString();await save(jobs);return j;}
export async function seedFactory(args:{datasets:DatasetSpec[];hypothesisIds?:string[];generations?:number;matrixRuns?:number;costs?:CostScenario[];seed?:string}){if(!args.datasets?.length)throw new Error("datasets are required");const seed=args.seed||"jarvis-factory";const jobs=[];const generations=Math.max(1,Math.min(Number(args.generations||3),20));const matrixRuns=Math.max(1,Math.min(Number(args.matrixRuns||500),500));for(const ds of args.datasets)jobs.push(await enqueueFactoryJob("regime-scan",{csvPath:ds.csvPath,window:100}));for(let g=0;g<generations;g++){jobs.push(await enqueueFactoryJob("matrix",{datasets:args.datasets,hypothesisIds:g===0?args.hypothesisIds:undefined,costs:args.costs,maxRuns:matrixRuns,seed:`${seed}|G${g}|matrix`}));jobs.push(await enqueueFactoryJob("evolution",{seed:`${seed}|G${g}|evolve`,offspring:12,elite:8}));}jobs.push(await enqueueFactoryJob("matrix",{datasets:args.datasets,costs:args.costs,maxRuns:matrixRuns,seed:`${seed}|final-matrix`}));jobs.push(await enqueueFactoryJob("portfolio",{minCoverage:Math.min(2,args.datasets.length),minPassRate:.6,challengers:8}));return{seed,generations,matrixRunsPerBatch:matrixRuns,plannedBacktestCapacity:(generations+1)*matrixRuns,enqueued:jobs.length,jobs};}
