import { randomUUID } from "node:crypto";
import type { ResearchHypothesis, StrategySpec } from "./types";
import { createHypothesis, getHypothesis, listHypotheses } from "./store";

export type StrategyGenome = {
  id: string;
  createdAt: string;
  generation: number;
  parents: string[];
  strategy: StrategySpec;
  mutations: string[];
  fingerprint: string;
};

function hashText(text: string) {
  let h = 2166136261 >>> 0;
  for (let i=0;i<text.length;i++) h=Math.imul(h^text.charCodeAt(i),16777619)>>>0;
  return h.toString(16).padStart(8,"0");
}
function seeded(seed:string,n:number){let h=2166136261>>>0;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;h^=Math.imul(n+1,2654435761);return(h>>>0)/4294967295;}
const discrete = new Set(["fast","slow","period","lookback","swingWindow","liquidityLookback","confirmBars"]);
function mutateParams(params:Record<string,number>,seed:string,offset:number){
  const out:Record<string,number>={}; let i=0;
  for(const [k,v] of Object.entries(params)){
    const r=seeded(seed,offset+i++), factor=1+(r*2-1)*0.28; let x=Math.max(0.0001,v*factor);
    if(discrete.has(k)) x=Math.max(1,Math.round(x));
    out[k]=Number(x.toFixed(discrete.has(k)?0:4));
  }
  if(out.fast&&out.slow&&out.fast>=out.slow)out.slow=Math.round(out.fast+Math.max(2,out.fast*.4));
  if(out.oversold)out.oversold=Math.max(10,Math.min(45,out.oversold));
  if(out.overbought)out.overbought=Math.max(55,Math.min(90,out.overbought));
  return out;
}
function clone(spec:StrategySpec):StrategySpec{return JSON.parse(JSON.stringify(spec)) as StrategySpec;}
function mutateSpec(spec:StrategySpec,seed:string,offset=0):StrategySpec{
  return {...clone(spec),params:mutateParams(spec.params||{},seed,offset),components:spec.components?.map((c,i)=>mutateSpec(c,seed,offset+i+31))};
}
function normalizeComponent(spec:StrategySpec):StrategySpec{
  const x=clone(spec); delete x.components; delete x.voteThreshold; return x;
}
export function makeHybrid(a:StrategySpec,b:StrategySpec,seed="jarvis-hybrid"):StrategySpec{
  const components:StrategySpec[]=[];
  const add=(s:StrategySpec)=>{ if(s.kind==="hybrid-vote"&&s.components) components.push(...s.components.map(normalizeComponent)); else components.push(normalizeComponent(s)); };
  add(a); add(b);
  const uniq=components.filter((c,i,arr)=>arr.findIndex(x=>x.kind===c.kind&&JSON.stringify(x.params)===JSON.stringify(c.params))===i).slice(0,6);
  return {kind:"hybrid-vote",params:{},timeframe:a.timeframe||b.timeframe||"M15",direction:"both",components:uniq.map((c,i)=>mutateSpec(c,seed,i*11)),voteThreshold:Math.max(1,Math.ceil(uniq.length*.5)),stopLossPct:a.stopLossPct||b.stopLossPct,takeProfitPct:a.takeProfitPct||b.takeProfitPct};
}
export async function crossoverHypotheses(args:{parentA:string;parentB:string;seed?:string;title?:string}){
  const [a,b]=await Promise.all([getHypothesis(args.parentA),getHypothesis(args.parentB)]); if(!a||!b) throw new Error("Both parent hypotheses are required.");
  const seed=args.seed||`${a.id}|${b.id}|${Date.now()}`;
  const strategy=a.strategy.kind===b.strategy.kind ? mutateSpec({...a.strategy,params:{...a.strategy.params,...Object.fromEntries(Object.keys(b.strategy.params).map((k,i)=>[k,seeded(seed,i)>.5?b.strategy.params[k]:a.strategy.params[k]??b.strategy.params[k]]))}},seed,1) : makeHybrid(a.strategy,b.strategy,seed);
  const generation=Math.max(a.generation||0,b.generation||0)+1;
  const child=await createHypothesis({title:args.title||`Genome crossover G${generation}: ${a.strategy.kind} × ${b.strategy.kind}`,claim:`A reproducible strategy genome combining evidence from ${a.id} and ${b.id} can retain out-of-sample expectancy across regimes and transaction-cost stress.`,rationale:"Generated by JARVIS Strategy Genome. It must independently pass all validation gates before any lifecycle promotion.",sourceRefs:[...new Set([...a.sourceRefs,...b.sourceRefs])],tags:[...new Set([...a.tags,...b.tags,"genome","crossover",strategy.kind==="hybrid-vote"?"hybrid":"same-family"])],strategy,parentHypothesisId:a.id,generation,evidenceScore:Math.min(1,((a.evidenceScore||.4)+(b.evidenceScore||.4))/2)});
  return {genome:{id:`genome_${randomUUID()}`,createdAt:new Date().toISOString(),generation,parents:[a.id,b.id],strategy,mutations:["crossover","seeded-parameter-mutation"],fingerprint:hashText(JSON.stringify(strategy))},hypothesis:child};
}
export async function evolvePopulation(args:{seed?:string;population?:number;elite?:number;offspring?:number}){
  const seed=args.seed||"jarvis-evolution"; const all=await listHypotheses(500); const tested=all.filter(h=>["validated","paper","shadow","promoted","rejected"].includes(h.status));
  const score=(h:ResearchHypothesis)=>(h.evidenceScore||0)+(["promoted","shadow","paper","validated"].indexOf(h.status)>=0?.4:0)+(h.generation||0)*.001;
  const parents=[...(tested.length?tested:all)].sort((a,b)=>score(b)-score(a)).slice(0,Math.max(2,Math.min(Number(args.elite||8),30)));
  if(parents.length<2) throw new Error("Need at least two hypotheses to evolve a population.");
  const count=Math.max(1,Math.min(Number(args.offspring||args.population||12),60)); const children=[];
  for(let i=0;i<count;i++){let ia=Math.floor(seeded(seed,i*7)*parents.length), ib=Math.floor(seeded(seed,i*7+1)*parents.length); if(ib===ia)ib=(ib+1)%parents.length; children.push(await crossoverHypotheses({parentA:parents[ia].id,parentB:parents[ib].id,seed:`${seed}|${i}`}));}
  return {seed,parents:parents.map(p=>({id:p.id,title:p.title,status:p.status,generation:p.generation||0})),offspring:children};
}
