import type { ToolCall } from "../types";
import { executeReachTool } from "../reach/tools";
import { pubmedSearch } from "../domains/pubmed";
type SwarmItem={source:string;ok:boolean;summary:string;data?:unknown;reliability:number;role:string};
export async function runResearchSwarm(args:{query:string;include?:string[];limit?:number}){
  const q=String(args.query||"").trim(); if(!q)throw new Error("query is required."); const include=(args.include?.length?args.include:["web","github","reddit","pubmed"]).slice(0,8); const limit=Math.max(1,Math.min(Number(args.limit||5),10)); const jobs:Promise<SwarmItem>[]=[];
  const wrap=async(source:string,reliability:number,role:string,call:ToolCall):Promise<SwarmItem>=>{const r=await executeReachTool(call);return{source,ok:r.ok,summary:r.summary,data:r.data,reliability,role};};
  if(include.includes("web")) jobs.push(wrap("exa-web",0.65,"broad discovery",{tool:"reach.search.exa",args:{query:q,limit}})); if(include.includes("github")) jobs.push(wrap("github",0.7,"code/implementation evidence",{tool:"reach.github.search",args:{query:q,limit}})); if(include.includes("reddit")) jobs.push(wrap("reddit",0.35,"community experience / weak evidence",{tool:"reach.social.search",args:{platform:"reddit",query:q,limit}})); if(include.includes("twitter")) jobs.push(wrap("twitter",0.25,"real-time discussion / weak evidence",{tool:"reach.social.search",args:{platform:"twitter",query:q,limit}})); if(include.includes("bilibili")) jobs.push(wrap("bilibili",0.3,"video/community discovery",{tool:"reach.social.search",args:{platform:"bilibili",query:q,limit}})); if(include.includes("pubmed")) jobs.push((async()=>{try{const data=await pubmedSearch(q,limit);return{source:"pubmed",ok:true,summary:`${data.length} PubMed citations`,data,reliability:0.9,role:"biomedical literature discovery"};}catch(e){return{source:"pubmed",ok:false,summary:e instanceof Error?e.message:"PubMed error",reliability:0.9,role:"biomedical literature discovery"};}})());
  const results=await Promise.all(jobs); const available=results.filter(x=>x.ok); return {query:q,generatedAt:new Date().toISOString(),results,coverage:{requested:include.length,available:available.length},rules:["Reliability is a source-class prior, not a truth score.","Claims require source-level verification before entering durable knowledge.","Community/social sources may generate hypotheses but cannot validate medical or trading efficacy by themselves."]};
}
