import fs from "node:fs/promises";import path from "node:path";import { randomUUID } from "node:crypto";
export type Belief={id:string;statement:string;confidence:number;support:string[];against:string[];domain?:string;status:"tentative"|"supported"|"contested"|"rejected";createdAt:string;updatedAt:string;lastReviewedAt:string};
const p=()=>path.resolve(process.env.JARVIS_BELIEFS_PATH||"./data/beliefs.json");
async function read():Promise<Belief[]>{try{return JSON.parse(await fs.readFile(p(),"utf8"))}catch{return[]}}
async function save(x:Belief[]){await fs.mkdir(path.dirname(p()),{recursive:true});await fs.writeFile(p(),JSON.stringify(x.slice(-10000),null,2),"utf8")}
function status(conf:number,s:number,a:number):Belief["status"]{if(conf<.2&&a>s)return"rejected";if(a>0&&s>0)return"contested";if(conf>=.65&&s>0)return"supported";return"tentative"}
export async function upsertBelief(args:{statement:string;confidence?:number;support?:string[];against?:string[];domain?:string}){if(!args.statement?.trim())throw new Error("statement required");const all=await read();const key=args.statement.trim().toLowerCase();const now=new Date().toISOString();let b=all.find(x=>x.statement.toLowerCase()===key);if(!b){b={id:`belief_${randomUUID()}`,statement:args.statement.trim(),confidence:Math.max(0,Math.min(1,args.confidence??.5)),support:[],against:[],domain:args.domain,status:"tentative",createdAt:now,updatedAt:now,lastReviewedAt:now};all.push(b)}b.support=[...new Set([...b.support,...(args.support||[])])];b.against=[...new Set([...b.against,...(args.against||[])])];if(args.confidence!=null)b.confidence=Math.max(0,Math.min(1,args.confidence));b.status=status(b.confidence,b.support.length,b.against.length);b.updatedAt=now;b.lastReviewedAt=now;await save(all);return b}
export async function listBeliefs(limit=100){return(await read()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,Math.max(1,Math.min(limit,500)))}
export async function reviseBelief(args:{id:string;delta:number;evidenceRef:string;direction:"support"|"against"}){const all=await read(),b=all.find(x=>x.id===args.id);if(!b)throw new Error("Belief not found.");const d=Math.max(-.5,Math.min(.5,args.delta));b.confidence=Math.max(0,Math.min(1,b.confidence+d));if(args.direction==="support")b.support=[...new Set([...b.support,args.evidenceRef])];else b.against=[...new Set([...b.against,args.evidenceRef])];b.status=status(b.confidence,b.support.length,b.against.length);b.updatedAt=new Date().toISOString();b.lastReviewedAt=b.updatedAt;await save(all);return b}
