import fs from "node:fs/promises";import path from "node:path";import { randomUUID } from "node:crypto";
export type ThoughtKind="question"|"hypothesis"|"reflection"|"goal"|"research"|"maintenance";
export type ThoughtStatus="queued"|"active"|"resolved"|"discarded"|"blocked";
export type Thought={id:string;kind:ThoughtKind;title:string;reason:string;importance:number;urgency:number;confidence:number;expectedValue:number;estimatedCost:number;risk:number;priority:number;status:ThoughtStatus;sourceRefs:string[];missionId?:string;createdAt:string;updatedAt:string;result?:string};
const p=()=>path.resolve(process.env.JARVIS_COGNITION_QUEUE_PATH||"./data/cognition-queue.json");
async function read():Promise<Thought[]>{try{return JSON.parse(await fs.readFile(p(),"utf8"))}catch{return[]}}
async function save(x:Thought[]){await fs.mkdir(path.dirname(p()),{recursive:true});await fs.writeFile(p(),JSON.stringify(x.slice(-5000),null,2),"utf8")}
const clamp=(n:number)=>Math.max(0,Math.min(1,n));const priority=(a:{importance:number;urgency:number;confidence:number;expectedValue:number;estimatedCost:number;risk:number})=>Math.round(100*clamp(a.importance*.25+a.urgency*.18+a.expectedValue*.27+a.confidence*.12+(1-a.estimatedCost)*.08+(1-a.risk)*.10));
export async function enqueueThought(args:{kind:ThoughtKind;title:string;reason:string;importance?:number;urgency?:number;confidence?:number;expectedValue?:number;estimatedCost?:number;risk?:number;sourceRefs?:string[];missionId?:string}){if(!args.title?.trim()||!args.reason?.trim())throw new Error("title and reason required");const all=await read();const duplicate=all.find(x=>["queued","active"].includes(x.status)&&x.title.toLowerCase()===args.title.trim().toLowerCase());if(duplicate)return duplicate;const base={importance:clamp(args.importance??.5),urgency:clamp(args.urgency??.4),confidence:clamp(args.confidence??.5),expectedValue:clamp(args.expectedValue??.5),estimatedCost:clamp(args.estimatedCost??.4),risk:clamp(args.risk??.2)};const now=new Date().toISOString();const t:Thought={id:`thought_${randomUUID()}`,kind:args.kind,title:args.title.trim(),reason:args.reason.trim(),...base,priority:priority(base),status:"queued",sourceRefs:args.sourceRefs||[],missionId:args.missionId,createdAt:now,updatedAt:now};all.push(t);await save(all);return t}
export async function listThoughts(limit=100,status?:ThoughtStatus){return(await read()).filter(x=>!status||x.status===status).sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt)).slice(0,Math.max(1,Math.min(limit,500)))}
export async function resolveThought(id:string,status:"resolved"|"discarded"|"blocked",result?:string){const all=await read(),t=all.find(x=>x.id===id);if(!t)throw new Error("Thought not found.");t.status=status;t.result=result;t.updatedAt=new Date().toISOString();await save(all);return t}
