import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { jarvisConfig } from "../config";

type Probe = { name: string; available: boolean; command: string; note: string };
function workspaceResolve(rel: string) { const root = path.resolve(jarvisConfig.workspacePath); const target = path.resolve(root, rel); if (target !== root && !target.startsWith(root + path.sep)) throw new Error("Path is outside JARVIS workspace."); return target; }
function runCmd(bin: string, args: string[], cwd: string, timeoutMs = 120000) { return new Promise<{ code: number; stdout: string; stderr: string }>((resolve, reject) => { const child = spawn(bin, args, { cwd, shell: false, windowsHide: true, env: process.env }); let stdout="", stderr=""; const timer=setTimeout(()=>{ child.kill(); reject(new Error(`${bin} timed out`)); }, timeoutMs); child.stdout.on("data", (d: unknown) => stdout += String(d).slice(0, 200000)); child.stderr.on("data", (d: unknown) => stderr += String(d).slice(0, 200000)); child.on("error", (e: Error) => { clearTimeout(timer); reject(e); }); child.on("close", (code: number | null) => { clearTimeout(timer); resolve({ code: code ?? -1, stdout, stderr }); }); }); }
async function probe(bin: string, args: string[], note: string): Promise<Probe> { try { const r=await runCmd(bin,args,jarvisConfig.workspacePath,10000); return { name:bin, command:[bin,...args].join(" "), available:r.code===0, note:r.code===0?note:`probe exit ${r.code}` }; } catch(e){ return { name:bin, command:[bin,...args].join(" "), available:false, note:e instanceof Error?e.message:"unavailable" }; } }
export async function engineeringAdaptersDoctor() { const rows = await Promise.all([ probe(process.env.JARVIS_NGSPICE_BIN || "ngspice", ["--version"], "SPICE circuit simulation"), probe(process.env.JARVIS_CCX_BIN || "ccx", ["-v"], "CalculiX finite-element solver"), probe(process.env.JARVIS_GMSH_BIN || "gmsh", ["-version"], "Gmsh meshing / preprocessing"), probe(process.env.JARVIS_OPENFOAM_BIN || "simpleFoam", ["-help"], "OpenFOAM steady CFD solver"), probe(jarvisConfig.pythonBin, ["-c", "import control; print(control.__version__)"], "python-control") ]); return { generatedAt:new Date().toISOString(), adapters:rows }; }
export async function runSpice(args:{ netlistPath:string; outputPath?:string }) { const file=workspaceResolve(args.netlistPath); await fs.access(file); const out=workspaceResolve(args.outputPath || `${args.netlistPath}.ngspice.log`); const bin=process.env.JARVIS_NGSPICE_BIN || "ngspice"; const r=await runCmd(bin,["-b","-o",out,file],path.dirname(file),120000); return { adapter:"ngspice", code:r.code, outputPath:path.relative(jarvisConfig.workspacePath,out), stdout:r.stdout.slice(-12000), stderr:r.stderr.slice(-12000) }; }
export async function runFea(args:{ inputPath:string }) { const file=workspaceResolve(args.inputPath); await fs.access(file); if (path.extname(file).toLowerCase() !== ".inp") throw new Error("CalculiX adapter requires an .inp file."); const job=path.basename(file,".inp"); const bin=process.env.JARVIS_CCX_BIN || "ccx"; const r=await runCmd(bin,["-i",job],path.dirname(file),180000); return { adapter:"calculix", code:r.code, job, cwd:path.relative(jarvisConfig.workspacePath,path.dirname(file)), stdout:r.stdout.slice(-16000), stderr:r.stderr.slice(-16000) }; }
export async function runCfd(args:{ casePath:string; solver?:string }) { const caseDir=workspaceResolve(args.casePath); const stat=await fs.stat(caseDir); if(!stat.isDirectory())throw new Error("CFD casePath must be a directory."); const solver=(args.solver || process.env.JARVIS_OPENFOAM_BIN || "simpleFoam").replace(/[^A-Za-z0-9_.-]/g,""); const allowed=(process.env.JARVIS_CFD_SOLVERS || "simpleFoam,pimpleFoam,pisoFoam,icoFoam").split(",").map((x: string)=>x.trim()).filter(Boolean); if(!allowed.includes(solver)) throw new Error(`Solver ${solver} is not in JARVIS_CFD_SOLVERS allowlist.`); const r=await runCmd(solver,["-case",caseDir],caseDir,300000); return { adapter:"openfoam", solver, code:r.code, casePath:path.relative(jarvisConfig.workspacePath,caseDir), stdout:r.stdout.slice(-20000), stderr:r.stderr.slice(-20000) }; }

export async function runMesh(args:{ geometryPath:string; dimension?:2|3; outputPath?:string }) { const file=workspaceResolve(args.geometryPath); await fs.access(file); const dim=args.dimension===2?2:3; const out=workspaceResolve(args.outputPath || `${args.geometryPath}.msh`); const bin=process.env.JARVIS_GMSH_BIN || "gmsh"; const r=await runCmd(bin,[file,`-${dim}`,"-o",out],path.dirname(file),180000); return { adapter:"gmsh", code:r.code, dimension:dim, outputPath:path.relative(jarvisConfig.workspacePath,out), stdout:r.stdout.slice(-12000), stderr:r.stderr.slice(-12000) }; }

export function simulateControl(args:{ A:number[][]; B:number[][]; C:number[][]; D?:number[][]; x0?:number[]; u:number[]; dt?:number; steps?:number }) { const A=args.A,B=args.B,C=args.C,D=args.D || C.map(()=>Array(args.u.length).fill(0)); const n=A.length, m=args.u.length, dt=Math.max(1e-6,Number(args.dt||0.01)), steps=Math.max(1,Math.min(Number(args.steps||1000),20000)); if(!n || A.some(r=>r.length!==n) || B.length!==n || B.some(r=>r.length!==m) || C.some(r=>r.length!==n) || D.some(r=>r.length!==m)) throw new Error("Invalid state-space dimensions."); let x=(args.x0 || Array(n).fill(0)).map(Number); if(x.length!==n)throw new Error("x0 dimension mismatch."); const out=[] as Array<{t:number;x:number[];y:number[]}>; for(let k=0;k<=steps;k++){ const y=C.map((row,ri)=>row.reduce((s,v,j)=>s+v*x[j],0)+D[ri].reduce((s,v,j)=>s+v*args.u[j],0)); if(k===0 || k===steps || k%Math.max(1,Math.floor(steps/200))===0) out.push({t:k*dt,x:[...x],y}); const dx=A.map((row,i)=>row.reduce((s,v,j)=>s+v*x[j],0)+B[i].reduce((s,v,j)=>s+v*args.u[j],0)); x=x.map((v,i)=>v+dx[i]*dt); } return { model:"continuous state-space, forward Euler", equation:"x_dot=Ax+Bu; y=Cx+Du", dt, steps, samples:out }; }
